[package]
name = "ashfire"
version = "0.1.0"
edition = "2021"
authors = ["Luna Amora <luna.mberry@gmail.com>"]
description = "Compiler for the Firelang language"
readme = "README.md"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.7", features = ["derive"] }
clap-verbosity-flag = "1.0.1"
anyhow = "1.0"
log = "0.4.17"
env_logger = "0.9.0"