ignore = ["firelib_macro"]
group_imports = "StdExternalCrate"
fn_params_layout = "Compressed"
imports_granularity = "Crate"
binop_separator = "Back"
newline_style = "Unix"
use_field_init_shorthand = true
overflow_delimited_expr = true
format_macro_matchers = true
format_macro_bodies = true
reorder_impl_items = true
inline_attribute_width = 40
struct_lit_width = 50
fn_call_width = 80
