ignore = ["firelib"]
fn_args_layout  = "Compressed"
imports_granularity = "Crate"
binop_separator = "Back"
newline_style = "Unix"
use_field_init_shorthand = true
overflow_delimited_expr = true
match_arm_blocks = false
format_strings = true
inline_attribute_width = 40
struct_lit_width = 50
fn_call_width = 80
