[package]
name = "wasm_backend"
version = "0.1.0"
description = "Wasm backend used by the Ashfire compiler"
edition.workspace = true
authors.workspace = true
readme.workspace = true
license-file.workspace = true

[dependencies]
anyhow = "1.0"
itertools = "0.10.5"
hexstring = "0.1.3"