[package]
name = "firelib"
version = "0.1.0"
edition = "2021"
authors = ["Luna Amora <luna.mberry@gmail.com>"]
description = "Library used by the Ashfire compiler"

[dependencies]
anyhow = "1.0"
